name: healthytics
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_database: ^11.3.2
  firebase_auth: ^5.4.2
  form_validation: ^3.2.0
  fluttertoast: ^8.2.11
  email_validator: ^3.0.0
  cached_network_image: ^3.4.1
  permission_handler: ^11.3.1
  flutter_slidable: ^4.0.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  file_picker: ^10.0.0
  image_picker: ^1.1.2
  flutter_datetime_picker_plus: ^2.2.0
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  toggle_switch: ^2.3.0
  firebase_storage: ^12.4.3
  flutter_sound: ^9.23.1
  flutter_expanded_tile: ^0.4.0
  google_maps_flutter: ^2.10.1
  just_audio: ^0.9.46
  carousel_slider: ^5.0.0
  another_xlider: ^3.0.2
  html: ^0.15.5
  flutter_quill: ^11.1.0
  delta_to_html: ^0.2.2
  flutter_widget_from_html: ^0.16.0
  syncfusion_flutter_charts: ^29.1.37+1
  awesome_notifications: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/images/inform.png
    - assets/images/user.png
    - assets/images/logo.png
    - assets/images/pw.png
    - assets/images/empty.png
    - assets/images/default.png
    - assets/images/home_bg.png
    - assets/images/upload.png

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/static/Raleway-Regular.ttf
          weight: 400
    - family: Raleway-Medium
      fonts:
        - asset: assets/fonts/Raleway/static/Raleway-Medium.ttf
          weight: 500
    - family: Raleway-SemiBold
      fonts:
        - asset: assets/fonts/Raleway/static/Raleway-SemiBold.ttf
          weight: 600
    - family: Raleway-Bold
      fonts:
        - asset: assets/fonts/Raleway/static/Raleway-Bold.ttf
          weight: 700
