// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZXGymkdx5mcWVDBhyh-E0TOc7kXU-9l0',
    appId: '1:203716023164:web:07923b68dadc9274888af9',
    messagingSenderId: '203716023164',
    projectId: 'ptsd-c364f',
    authDomain: 'ptsd-c364f.firebaseapp.com',
    databaseURL: 'https://ptsd-c364f-default-rtdb.firebaseio.com',
    storageBucket: 'ptsd-c364f.firebasestorage.app',
    measurementId: 'G-2P95R7G7DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvOcjp9zcY5C_JNhfx9yUvnrhGZbz9Ouk',
    appId: '1:664011362681:android:22b33dad1481273ea0dfa8',
    messagingSenderId: '664011362681',
    projectId: 'healytics-637c8',
    databaseURL: 'https://healytics-637c8-default-rtdb.firebaseio.com',
    storageBucket: 'healytics-637c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Znlw9hyig91BvWBS4dHid158_uY93bc',
    appId: '1:664011362681:ios:30541dfb3e2fcd88a0dfa8',
    messagingSenderId: '664011362681',
    projectId: 'healytics-637c8',
    databaseURL: 'https://healytics-637c8-default-rtdb.firebaseio.com',
    storageBucket: 'healytics-637c8.firebasestorage.app',
    iosBundleId: 'com.aries.healthy.tics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyEZqY1jSPRSj0-i-J4ebiCXBGOjRJfUk',
    appId: '1:203716023164:ios:8948e541b517e1b1888af9',
    messagingSenderId: '203716023164',
    projectId: 'ptsd-c364f',
    databaseURL: 'https://ptsd-c364f-default-rtdb.firebaseio.com',
    storageBucket: 'ptsd-c364f.firebasestorage.app',
    iosBundleId: 'com.aries.healthy.tics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZXGymkdx5mcWVDBhyh-E0TOc7kXU-9l0',
    appId: '1:203716023164:web:ff95f44ce734b118888af9',
    messagingSenderId: '203716023164',
    projectId: 'ptsd-c364f',
    authDomain: 'ptsd-c364f.firebaseapp.com',
    databaseURL: 'https://ptsd-c364f-default-rtdb.firebaseio.com',
    storageBucket: 'ptsd-c364f.firebasestorage.app',
    measurementId: 'G-M3B8ME9G5Z',
  );
}